# Generated by Django 5.1.5 on 2025-02-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_stockquote_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockquote',
            old_name='number_of_trades',
            new_name='no_of_transactions',
        ),
    ]
