# Generated by Django 5.1.5 on 2025-02-18 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_rename_number_of_trades_stockquote_no_of_transactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockquote',
            old_name='high_price',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='stockquote',
            old_name='close_price',
            new_name='high',
        ),
        migrations.RenameField(
            model_name='stockquote',
            old_name='low_price',
            new_name='low',
        ),
        migrations.RenameField(
            model_name='stockquote',
            old_name='open_price',
            new_name='open',
        ),
    ]
