# Generated by Django 5.1.5 on 2025-02-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_rename_high_price_stockquote_close_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockquote',
            unique_together={('company', 'time')},
        ),
    ]
